"""create applications table

Revision ID: 6599383a936b
Revises: e3bc8039402e
Create Date: 2026-09-04 19:26:11.954030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6599383a936b'
down_revision: Union[str, Sequence[str], None] = 'e3bc8039402e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False),
    sa.Column('scheme_name', sa.String(length=200), nullable=False),
    sa.Column('college_name', sa.String(length=200), nullable=False),
    sa.Column('board', sa.String(length=100), nullable=False),
    sa.Column('class_12_year', sa.Integer(), nullable=False),
    sa.Column('stream', sa.String(length=100), nullable=False),
    sa.Column('marks_percentage', sa.String(length=20), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('course_type', sa.String(length=100), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('annual_family_income', sa.Integer(), nullable=False),
    sa.Column('other_scholarship', sa.String(length=10), nullable=False),
    sa.Column('regular_course', sa.String(length=10), nullable=False),
    sa.Column('is_diploma', sa.String(length=10), nullable=False),
    sa.Column('drop_after_class_12', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_application_number'), 'applications', ['application_number'], unique=True)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_student_profile_id'), 'applications', ['student_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_student_profile_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_number'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
