"""add model relationships

Revision ID: 94e7dd80efe2
Revises: 60ce76c85a01
Create Date: 2026-09-04 20:08:33.298390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e7dd80efe2'
down_revision: Union[str, Sequence[str], None] = '60ce76c85a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_findings', 'finding_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ai_findings', 'severity',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ai_findings', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('ai_findings', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ai_summaries', 'summary_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('applications', sa.Column('scheme_id', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('institute_id', sa.Integer(), nullable=True))
    op.alter_column('applications', 'scheme_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('applications', 'college_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('applications', 'board',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('applications', 'class_12_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('applications', 'stream',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('applications', 'marks_percentage',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('applications', 'course_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('applications', 'course_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('applications', 'admission_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('applications', 'annual_family_income',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('applications', 'other_scholarship',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('applications', 'regular_course',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('applications', 'is_diploma',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('applications', 'drop_after_class_12',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_index(op.f('ix_applications_institute_id'), 'applications', ['institute_id'], unique=False)
    op.create_index(op.f('ix_applications_scheme_id'), 'applications', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_foreign_key(None, 'applications', 'institutes', ['institute_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'schemes', ['scheme_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'student_profiles', ['student_profile_id'], ['id'])
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('documents', 'ocr_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('documents', 'classification_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('institutes', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('officer_profiles', 'designation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_foreign_key(None, 'officer_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('schemes', 'is_active',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_foreign_key(None, 'student_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('verification_actions', 'level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('verification_actions', 'action',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_actions', 'action',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('verification_actions', 'level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.alter_column('schemes', 'is_active',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_constraint(None, 'officer_profiles', type_='foreignkey')
    op.alter_column('officer_profiles', 'designation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('institutes', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('documents', 'classification_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('documents', 'ocr_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_scheme_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_institute_id'), table_name='applications')
    op.alter_column('applications', 'drop_after_class_12',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('applications', 'is_diploma',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('applications', 'regular_course',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('applications', 'other_scholarship',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('applications', 'annual_family_income',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'admission_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'course_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('applications', 'course_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('applications', 'marks_percentage',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('applications', 'stream',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('applications', 'class_12_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'board',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('applications', 'college_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('applications', 'scheme_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('applications', 'institute_id')
    op.drop_column('applications', 'scheme_id')
    op.alter_column('ai_summaries', 'summary_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ai_findings', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ai_findings', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('ai_findings', 'severity',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ai_findings', 'finding_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
