"""create officer profiles table

Revision ID: e3bc8039402e
Revises: 44f960d10be6
Create Date: 2026-09-04 13:14:01.405768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3bc8039402e'
down_revision: Union[str, Sequence[str], None] = '44f960d10be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('institute_name', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officer_profiles_id'), 'officer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_officer_profiles_user_id'), 'officer_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_officer_profiles_user_id'), table_name='officer_profiles')
    op.drop_index(op.f('ix_officer_profiles_id'), table_name='officer_profiles')
    op.drop_table('officer_profiles')
    # ### end Alembic commands ###
